<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ ucfirst($type) }} Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #111827;
            background: #ffffff;
            margin: 32px;
        }
        .header {
            border-bottom: 2px solid #111827;
            padding-bottom: 12px;
            margin-bottom: 20px;
        }
        h1 {
            margin: 0 0 8px;
            font-size: 28px;
        }
        .meta {
            color: #4b5563;
            font-size: 14px;
        }
        .summary {
            display: flex;
            gap: 16px;
            margin: 20px 0;
            flex-wrap: wrap;
        }
        .card {
            border: 1px solid #d1d5db;
            border-radius: 8px;
            padding: 12px 16px;
            min-width: 150px;
            background: #f9fafb;
        }
        .chart-box {
            border: 1px solid #d1d5db;
            border-radius: 8px;
            background: #f9fafb;
            padding: 16px;
            margin: 20px 0;
        }
        .chart-bars {
            display: flex;
            align-items: end;
            gap: 8px;
            height: 180px;
            margin-top: 12px;
        }
        .chart-bar-wrap {
            flex: 1;
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 6px;
            height: 100%;
            color: #6b7280;
            font-size: 10px;
            text-align: center;
        }
        .chart-bar {
            width: 100%;
            max-width: 34px;
            min-height: 8px;
            border-radius: 6px 6px 0 0;
            background: linear-gradient(180deg, #60a5fa 0%, #2563eb 100%);
        }
        .label {
            display: block;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 1px;
            color: #6b7280;
            margin-bottom: 6px;
        }
        .value {
            font-weight: 700;
            font-size: 22px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
        }
        th, td {
            border: 1px solid #d1d5db;
            padding: 10px 12px;
            text-align: left;
            font-size: 13px;
        }
        th {
            background: #f3f4f6;
        }
        @media print {
            body { margin: 0; }
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $report['title'] }}</h1>
        <div class="meta">
            Generated by {{ auth()->user()->name }} · Period: {{ ucfirst($range) }}
        </div>
    </div>

    <div class="summary">
        @foreach($report['stats'] as $stat)
            <div class="card">
                <span class="label">{{ $stat['label'] }}</span>
                <span class="value">{{ $stat['value'] }}</span>
            </div>
        @endforeach
    </div>

    @if(!empty($report['chart']['labels'] ?? []))
        <div class="chart-box">
            <strong>Analytics</strong>
            <div class="chart-bars">
                @php
                    $chart = $report['chart'] ?? ['labels' => [], 'values' => []];
                    $values = $chart['values'] ?? [];
                    $labels = $chart['labels'] ?? [];
                    $max = max(max($values), 1);
                @endphp
                @foreach($values as $index => $value)
                    @php $height = max(10, ($value / $max) * 100); @endphp
                    <div class="chart-bar-wrap">
                        <div class="chart-bar" style="height: {{ $height }}%;"></div>
                        <span>{{ $labels[$index] ?? '' }}</span>
                    </div>
                @endforeach
            </div>
        </div>
    @endif

    @if($report['empty'])
        <p>No data available for this period.</p>
    @else
        <table>
            <thead>
                <tr>
                    @if($type === 'payment')
                        <th>Member</th>
                        <th>Type</th>
                        <th>Date</th>
                        <th>Method</th>
                        <th>Amount</th>
                    @elseif($type === 'attendance')
                        <th>Name</th>
                        <th>Role</th>
                        <th>Date</th>
                        <th>Time In</th>
                        <th>Time Out</th>
                        <th>Duration</th>
                    @elseif($type === 'member')
                        <th>Name</th>
                        <th>Email</th>
                        <th>Date Joined</th>
                        <th>Plan</th>
                        <th>Status</th>
                    @else
                        <th>Member</th>
                        <th>Session</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Instructor</th>
                    @endif
                </tr>
            </thead>
            <tbody>
                @foreach($report['rows'] as $row)
                    <tr>
                        @if($type === 'payment')
                            <td>{{ $row['name'] }}</td>
                            <td>{{ $row['type'] }}</td>
                            <td>{{ $row['date'] }}</td>
                            <td>{{ $row['method'] }}</td>
                            <td>{{ $row['amount'] }}</td>
                        @elseif($type === 'attendance')
                            <td>{{ $row['name'] }}</td>
                            <td>{{ $row['role'] }}</td>
                            <td>{{ $row['date'] }}</td>
                            <td>{{ $row['time_in'] }}</td>
                            <td>{{ $row['time_out'] }}</td>
                            <td>{{ $row['duration'] }}</td>
                        @elseif($type === 'member')
                            <td>{{ $row['name'] }}</td>
                            <td>{{ $row['email'] }}</td>
                            <td>{{ $row['date'] }}</td>
                            <td>{{ $row['plan'] }}</td>
                            <td>{{ $row['status'] }}</td>
                        @else
                            <td>{{ $row['name'] }}</td>
                            <td>{{ $row['title'] }}</td>
                            <td>{{ $row['date'] }}</td>
                            <td>{{ $row['status'] }}</td>
                            <td>{{ $row['instructor'] }}</td>
                        @endif
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="no-print" style="margin-top: 24px;">
        <button type="button" onclick="window.print()" style="padding: 10px 16px; cursor: pointer;">Print / Save as PDF</button>
    </div>
</body>
</html>
